"""
Django settings for iSkyLIMS project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import os
from datetime import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7v+x&yv97fn28a1hkqhqo!68wu0%nvtk(yd2@inimh4-k10@gi'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
# pnl anyadimos estos parametros
DEBUG = True
#SECURE_CONTENT_TYPE_NOSNIFF = True
#SECURE_BROWSER_XSS_FILTER = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True
#X_FRAME_OPTIONS = 'DENY'
ALLOWED_HOSTS = ['localhost','127.0.0.1','172.16.30.51','192.168.2.105']


# Application definition

INSTALLED_APPS = [
    'iSkyLIMS_core',
    'iSkyLIMS_clinic',
    'iSkyLIMS_wetlab',
    'iSkyLIMS_drylab',
    'django_utils',
    'mptt',
    'crispy_forms',
    'django_crontab',
    'django_mptt_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_comments',
    'django_extensions',
    'tagging',
    'rest_framework',
]

APPS_NAMES = [
    ['iSkyLIMS_clinic','Clinic'],
    ['iSkyLIMS_wetlab','Wet Lab'],
    ['iSkyLIMS_drylab','Bioinformatics Services']
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iSkyLIMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/documents/drylab/services_templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'zinnia.context_processors.version',  # Optional
            ],
        },
    },
]

WSGI_APPLICATION = 'iSkyLIMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST':'127.0.0.1',
        'USER': 'django',
        'PASSWORD':'Passdjang0',
        'PORT':'3306',
        'NAME': 'iSkyLIMS',
        'TEST': {
            'NAME': 'iSkyLIMS',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'
#TIME_ZONE = 'UTC' --> 'Europe/Madrid' for forms such as 'blog entries'
TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

#  Media settings
MEDIA_URL = '/documents/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'documents/')

## Crispy forms settings
CRISPY_TEMPLATE_PACK = "bootstrap3"

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # During development only
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# EMAIL settings
EMAIL_HOST = 'stmp.gmx.com'
EMAIL_PORT = '465'
EMAIL_HOST_USER = 'iskylims@gmx.com'
EMAIL_HOST_PASSWORD = '0!mZMzMVDlyNJ'
EMAIL_USE_TLS =  True
ALLOWED_EMAIL_DOMAINS = ['incliva.es']

# Archivos de log utilizados. Idealmente se deberían ir creando nuevos ya que pueden llegar a ser muy grandes.
LOG_CRONTAB_FILE = os.path.join(BASE_DIR, 'logs', 'crontab_looking_for_new_runs.log') # Antiguamente crontab
# LOG_CLEAN_FILE = os.path.join(BASE_DIR, 'logs', 'crontab_cleanup.log') # Esto a día de hoy no se usa ya que no se ejecuta esta tarea
LOG_BACKUP_FILE = os.path.join(BASE_DIR, 'logs', 'crontab_copy_rsync_crontab.log') # Antiguamente backup_rsync

# Crontab settings
CRONJOBS = [
    ('*/15 * * * *', 'iSkyLIMS_wetlab.cron.looking_for_new_runs', '>>' + LOG_CRONTAB_FILE),
    # ('0 0 * * FRI', 'iSkyLIMS_wetlab.cron.delete_invalid_run', '>>' + LOG_CLEAN_FILE),
    ('0 * * * *', 'iSkyLIMS_wetlab.utils.handling_copy_run.copy_rsync_crontab', '>>' + LOG_BACKUP_FILE), # se ejecuta cada hora
]

CRONTAB_COMMAND_SUFFIX = '2>&1' # Con esto se redirige la salida de error a la salida estandar para que se pueda ver en el log

# Zinnia blog-tutorial
# Note: according to django doc, SITE_ID is used for multi-site confs.
# Nevertheless, added here following zinnia doc
# (http://docs.django-blog-zinnia.com/en/latest/getting-started/install.html)
SITE_ID =1

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
DATA_UPLOAD_MAX_MEMORY_SIZE = 10000000
